apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
data:
  index.html: |
    <html>
    <head><title>Hello World</title></head>
    <body><h1>Hello World from Minikube!</h1></body>
    </html>

