apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
data:
  index.html: |
    <html>
    <head><title><>Hello K8s</title></head>
    <body><h3>Hello K8s from Minikube!</h3><hr></body>
    </html>

