namePrefix: staging-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: replica-patch.yaml

configMapGenerator:
  - name: htmldata
    env: config.properties
